name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true # Needed if you use Git LFS
      - name: Push to Hugging Face Hub
        uses: nateraw/huggingface-sync-action@v0.0.5
        with:
          github_repo_id: ${{ github.repository }}
          huggingface_repo_id: 'Testingar/test-hive-buzzing-with-quality'
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_type: 'space' # or 'model', 'dataset'
